---
- name: Start logspout docker container
  docker_container:
    name: logspout
    image: gliderlabs/logspout:master
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "syslog+tls://{{ papertrail_host_prod if 'web' in inventory_hostname else papertrail_host_staging }}:{{ papertrail_port_prod if 'web' in inventory_hostname else papertrail_port_staging }}"
    env:
      SYSLOG_HOSTNAME: "{{ ansible_hostname }}"
    networks:
      - name: sol-network
    ports:
      - "8000:80"
