---
- name: Restart logdna-agent
  ansible.builtin.systemd:
    name: logdna-agent
    state: restarted
    daemon_reload: true

- name: Restart logdna container
  community.docker.docker_container:
    name: logdna
    restart: true
