---
# You may change these as needed.

sdk_tools_url: "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
android_home: "/opt/android-sdk"
avd_name: "KindleAVD"
sdk_api_level: "35"
# Change to Google Play system image which includes ARM translation libraries
sys_img: "system-images;android-{{ sdk_api_level }};google_apis_playstore;x86_64"
# emulator_package: "emulator-arm64"
emulator_package: "emulator"
platform_tools_package: "platform-tools"
build_tools_version: "35.0.0"
# Example build-tools path: build-tools;35.0.0
build_tools_package: "build-tools;{{ build_tools_version }}"
kindle_package_path: "com.amazon.kindle_8.113.0.100(2.0.29451.0)-1285953011_minAPI28(arm64-v8a)(nodpi).com.apk"

# If you want a custom skin or density:
device_skin: "pixel_5"
sdcard_size: "2G"
avd_heap_size: "512"

# Headless emulator options:
emulator_extra_opts: "-no-audio -no-window -gpu swiftshader_indirect"

# If you need to accept multiple licenses, you can add them here:
sdk_licenses:
  - "android-sdk-license"
  - "android-sdk-preview-license"
  - "intel-android-extra-license"
